In [1]:
#import pandas
import pandas as pd

In [2]:
#import dataset
df = pd.read_csv(r"C:\Users\gadis\Downloads\churn bank\Churn_Modelling.csv")

In [4]:
#check shape of dataset
df.shape

(10000, 14)

In [5]:
#check datatypes of different columns..all datatypes are correct
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
#check if there are any nulls in the dataset...there were no nulls
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
#check if there are any duplicate rows....there were no duplicates
df.duplicated().sum()

np.int64(0)

In [8]:
#take a statistical view of the dataset
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000


In [14]:
#check for validation issues in the Geography Column..Column perfectly fine
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [17]:
#check for validation issues in the Gender Column..Column perfectly fine
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [26]:
#check for validation issues in the CreditScore Column..Column perfectly fine
(df['CreditScore']<0).sum()

np.int64(0)

In [31]:
#check for validation issues in the Age Column..Column perfectly fine
(df['Age']<18).sum()

np.int64(0)

In [35]:
#check for validation issues in the Tenure Column..Column perfectly fine
(df['Tenure']<0).sum()

np.int64(0)

In [38]:
#check for validation issues in the Balance Column..Column perfectly fine
(df['Balance']<0).sum()

np.int64(0)

In [40]:
#check for validation issues in the NumofProducts Column..Column perfectly fine
(df['NumOfProducts']<0).sum()

np.int64(0)

In [49]:
#check for validation issues in the HasCrCard Column..Column perfectly fine
df['HasCrCard'].unique()

array([1, 0])

In [50]:
#check for validation issues in the IsActiveMember Column..Column perfectly fine
df['IsActiveMember'].unique()

array([1, 0])

In [46]:
#check for validation issues in the EstimatedSalary Column..Column perfectly fine
(df['EstimatedSalary']<0).sum()

np.int64(0)

In [48]:
#check for validation issues in the Exited Column..Column perfectly fine
df['Exited'].unique()

array([1, 0])

In [56]:
#check for validation issues in the Surname Column..Fixed some standardization issues
df['Surname'] = df['Surname'].str.title().str.strip()

In [57]:
df.to_csv(r"C:\Users\gadis\Downloads\churn bank\Clean_bank_churn.csv")